### ISSUE TITLE
Error: Class "Sample" is reserved for use by Microsoft

### ISSUE THREAD

**Issue by forderud** [xxandy/USB_UDE_Sample#13]
I'm experiencing the following error when attempting to build `hostude` with Visual Studio 2022 and WDK 10.0.22621.311:
```
>UDEFX_host\driver\hostude.inx(21-21): error 1284: Class "Sample" is reserved for use by Microsoft.
>UDEFX_host\driver\hostude.inx(30-30): error 1285: Cannot specify [ClassInstall32] section for Microsoft-defined class.>UDEFX_host\driver\hostude.inx(21-21): error 1284: Class "Sample" is reserved for use by Microsoft.
>UDEFX_host\driver\hostude.inx(30-30): error 1285: Cannot specify [ClassInstall32] section for Microsoft-defined class.
```

These errors are caused by "recent" hardening of the INF validator explained in [INF Validation Errors and Warnings](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/inf-validation-errors-and-warnings)

This problem can be fixed by changing the `Class` name and `ClassGuid` in `hostude.inx`. I'm assuming that the driver doesn't adhere to any well-known class since `Sample` is currently used, so an arbitrary class name can probably be used.

**Comment by forderud** [comment]
Possible `hostude.inx` fix with "hostude" as class name and a new unique generated GUID:
```
Class=hostude
ClassGuid={EB126E34-0F84-49B5-9493-E32C95B03305}
```

Disclaimer: I haven't tested the generated driver after applying this change, so I cannot guarantee that the driver still functions as intended.

**Comment by xxandy** [comment]
This one is fixed, right?

**Comment by forderud** [comment]
> This one is fixed, right?

Correct. The reported problem is now fixed.

**Comment by S16201512** [comment]
> > 这个是修好的吧？
> 
> 正确。报告的问题现已修复。

Unfortunately, I am now in a win11 environment, based on VS2019+SDK10.2200000+WDK10.22000.
I compilie the echo samples driver, and the error "Class "Sample" is reserved for use by Microsoft" still appears.

why? I need  help @forderud

**Comment by forderud** [comment]
> Unfortunately, I am now in a win11 environment, based on VS2019+SDK10.2200000+WDK10.22000. I compilie the echo samples driver, and the error "Class "Sample" is reserved for use by Microsoft" still appears.
> 
> why? I need help @forderud

That sounds strange to me. If you take a look in the [hostude.inx](https://github.com/xxandy/USB_UDE_Sample/blob/master/UDEFX_host/driver/hostude.inx) then you'll see that `Class=Sample` have now been replaced by `Class=hostude`. There's no longer any "Sample" class mentioned that Visual Studio can complain about.

I just tried to build all projects in this repo and did not experience any problems.
